name: Quality Gates v2

on:
  workflow_dispatch

jobs:

  Cache-Dependencies:
    runs-on: windows-latest
    steps:
      - name: Install Node Js v12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Get Code From Git Repository
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: movie-finder-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies / Third party packages
        run: npm ci
      - name: Install Dependencies
        run: npm ci
      - name: Display File/Dir Structure
        run: dir

  Prettier-check:
    needs: Cache-Dependencies
    runs-on: windows-latest
    steps:
      - name: Install Node Js v12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Get Code From Git Repository
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: movie-finder-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies / Third party packages
        run: npm ci
      - name: Run Prettier check
        run: npm run prettier-check
        
  Style-Lint:
    needs: Cache-Dependencies
    runs-on: windows-latest
    steps:
      - name: Install Node Js v12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Get Code From Git Repository
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: movie-finder-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies / Third party packages
        run: npm ci
      - name: Run Style Lint
        run: npm run stylelint-check
        
  Eslint-Check:
    needs: Cache-Dependencies
    runs-on: windows-latest
    steps:
      - name: Install Node Js v12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Get Code From Git Repository
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: movie-finder-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies / Third party packages
        run: npm ci
      - name: Run Eslint
        run:  npm run eslint-check
        
  Run-Linting:
    needs: Cache-Dependencies
    runs-on: windows-latest
    steps:
      - name: Install Node Js v12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Get Code From Git Repository
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: movie-finder-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies / Third party packages
        run: npm ci
      - name: Linting project
        run: npm run lint
    
  Run-Unit-Tests:
    needs: Cache-Dependencies
    runs-on: windows-latest
    steps:
      - name: Install Node Js v12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
        id: setup-chrome
      - name: Display Chrome Version
        run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          chrome --version
      - name: Get Code From Git Repository
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: movie-finder-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies / Third party packages
        run: npm ci
      - name: Run Unit Tests
        run: npm run test
        
  Run-E2E-tests:
    needs: Cache-Dependencies
    runs-on: windows-latest
    steps:
      - name: Install Node Js v12
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
        id: setup-chrome
      - name: Display Chrome Version
        run: |
          echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
          chrome --version
      - uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &
      - name: Get Code From Git Repository
        uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: movie-finder-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies / Third party packages
        run: npm ci
      - name: Run E2E tests
        run: npm run ng e2e --webdriver-update=false
